[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
optimizer = true
optimizer_runs = 1

# Lisk Sepolia Testnet
[rpc_endpoints]
lisk_sepolia = "https://lisk-sepolia.drpc.org"

[etherscan]
lisk_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=4202" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
