[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
optimizer = true
optimizer_runs = 1

# Arbitrum Sepolia Testnet
[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_RPC_URL}"

[etherscan]
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
